### ISSUE TITLE
Cannot run experiments without sample gold standard

### ISSUE THREAD

**Issue by michelole** [JULIELab/trec-pm#11]
```
Exception in thread "Thread-0" java.lang.UnsupportedOperationException: No available sample gold standard.
	at at.medunigraz.imi.bst.trec.experiment.Experiment.getSampleGoldStandard(Experiment.java:201)
	at at.medunigraz.imi.bst.trec.experiment.Experiment.run(Experiment.java:131)
```

**Comment by khituras** [comment]
Please provide more information on the exact experiment configuration for reproducibility.

**Comment by michelole** [comment]
Try to run `ClinicalTrialsExperimenter` with `GoldStandard.INTERNAL` and year 2019.
